name: UI Tests

on: [push]

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: isbang/compose-action@v1.4.1

      - name: Install Java (for Allure)
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre-headless
          java -version

      - name: Run UI tests
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          LOGIN=${{ secrets.LOGIN }} PASSWORD=${{ secrets.PASSWORD }} docker-compose up --exit-code-from regression
        continue-on-error: true

      - name: Generate Allure report
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          sudo tar -zxvf allure-2.24.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.24.0/bin/allure /usr/bin/allure
          
          # Генерируем отчет локально
          allure generate allure-results --clean -o allure-report